// <auto-generated />
using Christofel.Api.Ctu.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Christofel.Api.Migrations
{
    [DbContext(typeof(ApiCacheContext))]
    partial class ApiCacheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Christofel.Api.Ctu.Database.AssignRole", b =>
                {
                    b.Property<long>("AssignRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Add")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("GuildDiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UserDiscordId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("AssignRoleId");

                    b.ToTable("AssignRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
