services:
  database:
    image: mariadb:10.6.3
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql/data

volumes:
  db-data:
