<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>nullable</WarningsAsErrors>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <LangVersion>11</LangVersion>

        <AssemblyVersion>1.1.1</AssemblyVersion>

        <FileVersion>1.1.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Libs\Christofel.Helpers\Christofel.Helpers.csproj" />
        <ProjectReference Include="..\..\Core\Christofel.Common\Christofel.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.0.0" />
        <PackageReference Include="Remora.Discord.API.Abstractions" Version="84.0.0" />
        <PackageReference Include="Remora.Discord.Commands" Version="30.0.0" />
    </ItemGroup>

</Project>
