<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Christofel.Remora</RootNamespace>
        <Nullable>enable</Nullable>
        <LangVersion>11</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Remora.Discord.Gateway" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Christofel.Plugins\Christofel.Plugins.csproj" />
    </ItemGroup>

</Project>
