// <auto-generated />
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Christofel.Common.Migrations
{
    /// <inheritdoc />
    public partial class AddUsernameRoleAssignment : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "UsernameRoleAssignment",
                schema: "Core",
                columns: table => new
                {
                    UsernameRoleAssignmentId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Username = table.Column<string>(type: "longtext", nullable: false)
                        .Annotation("MySql:CharSet", "utf8mb4"),
                    AssignmentId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UsernameRoleAssignment", x => x.UsernameRoleAssignmentId);
                    table.ForeignKey(
                        name: "FK_UsernameRoleAssignment_RoleAssignment_AssignmentId",
                        column: x => x.AssignmentId,
                        principalSchema: "Core",
                        principalTable: "RoleAssignment",
                        principalColumn: "RoleAssignmentId",
                        onDelete: ReferentialAction.Restrict);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateIndex(
                name: "IX_UsernameRoleAssignment_AssignmentId",
                schema: "Core",
                table: "UsernameRoleAssignment",
                column: "AssignmentId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UsernameRoleAssignment",
                schema: "Core");
        }
    }
}
