// <auto-generated />
using Christofel.CoursesLib.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Christofel.CoursesLib.Migrations
{
    [DbContext(typeof(CoursesContext))]
    [Migration("20221006185143_AddCoursesGroup")]
    partial class AddCoursesGroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Courses")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Christofel.CoursesLib.Database.CourseAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ChannelName")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CourseKey")
                        .IsUnique();

                    b.HasIndex("DepartmentKey");

                    b.ToTable("CourseAssignments", "Courses");
                });

            modelBuilder.Entity("Christofel.CoursesLib.Database.CourseGroupAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("CourseGroupAssignment", "Courses");
                });

            modelBuilder.Entity("Christofel.CoursesLib.Database.DepartmentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("DepartmentKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentKey")
                        .IsUnique();

                    b.ToTable("DepartmentAssignment", "Courses");
                });

            modelBuilder.Entity("Christofel.CoursesLib.Database.CourseAssignment", b =>
                {
                    b.HasOne("Christofel.CoursesLib.Database.CourseGroupAssignment", "GroupAssignment")
                        .WithMany("Courses")
                        .HasForeignKey("ChannelId")
                        .HasPrincipalKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Christofel.CoursesLib.Database.DepartmentAssignment", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentKey")
                        .HasPrincipalKey("DepartmentKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("GroupAssignment");
                });

            modelBuilder.Entity("Christofel.CoursesLib.Database.CourseGroupAssignment", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Christofel.CoursesLib.Database.DepartmentAssignment", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
