<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>

        <IsPackable>false</IsPackable>

        <Nullable>enable</Nullable>

        <LangVersion>12</LangVersion>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="KosApi" Version="1.4.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
        <PackageReference Include="UsermapApi" Version="1.1.0" />
        <PackageReference Include="AwesomeAssertions" Version="9.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="xunit.v3" Version="3.0.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Christofel.Common\Christofel.Common.csproj" />
        <ProjectReference Include="..\..\Libs\Christofel.CtuAuth\Christofel.CtuAuth.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Ctu\Auth\CtuAuthProcessLogicTests.Data.cs">
            <DependentUpon>CtuAuthProcessLogicTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAtuhProcessLogicTests.Exceptions.cs">
            <DependentUpon>CtuAuthProcessLogicTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAuthProcessLogicTests.TokenApi.cs">
            <DependentUpon>CtuAuthProcessLogicTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAuthProcessLogicTests.Continuity.cs">
            <DependentUpon>CtuAuthProcessLogicTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAuthProcessLogicTests.Returns.cs">
            <DependentUpon>CtuAuthProcessLogicTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAuthProcessConditionTests.UsernameMatches.cs">
            <DependentUpon>CtuAuthProcessConditionTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAuthProcessConditionTests.NoDuplicate.cs">
            <DependentUpon>CtuAuthProcessConditionTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAuthProcessConditionTests.MemberMatchesUser.cs">
            <DependentUpon>CtuAuthProcessConditionTests.cs</DependentUpon>
        </Compile>
        <Compile Update="Ctu\Auth\CtuAuthProcessConditionTests.UsernameFilled.cs">
            <DependentUpon>CtuAuthProcessConditionTests.cs</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <Using Include="Xunit" />
    </ItemGroup>

</Project>
