<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>1.1.0</AssemblyVersion>
        <FileVersion>1.1.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Christofel.Common\Christofel.Common.csproj" />
      <ProjectReference Include="..\Christofel.Helpers\Christofel.Helpers.csproj" />
      <ProjectReference Include="..\Christofel.OAuth\Christofel.OAuth.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="KosApi" Version="1.4.0" />
      <PackageReference Include="Remora.Results" Version="8.0.0" />
      <PackageReference Include="System.Linq.Async" Version="6.0.3" />
      <PackageReference Include="UsermapApi" Version="1.1.0" />
    </ItemGroup>

</Project>
