// <auto-generated />
using System;
using Christofel.Management.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Christofel.Management.Migrations
{
    [DbContext(typeof(ManagementContext))]
    [Migration("20211128134746_AddResendRules")]
    partial class AddResendRules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Management")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Christofel.Management.Database.Models.ResendRule", b =>
                {
                    b.Property<int>("ResendRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("FromChannel")
                        .HasColumnType("bigint");

                    b.Property<long>("ToChannel")
                        .HasColumnType("bigint");

                    b.HasKey("ResendRuleId");

                    b.ToTable("ResendRule", "Management");
                });

            modelBuilder.Entity("Christofel.Management.Database.Models.TemporalSlowmode", b =>
                {
                    b.Property<int>("TemporalSlowmodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DeactivationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("ReturnInterval")
                        .HasColumnType("time(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("TemporalSlowmodeId");

                    b.ToTable("TemporalSlowmode", "Management");
                });
#pragma warning restore 612, 618
        }
    }
}
