// <auto-generated />
using Christofel.Api.Ctu.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Christofel.Api.Migrations
{
    [DbContext(typeof(ApiCacheContext))]
    [Migration("20210829081908_ChangeUlongsToSnowflakes")]
    partial class ChangeUlongsToSnowflakes
    {
        /// <inheritdoc/>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Christofel.Api.Ctu.Database.AssignRole", b =>
                {
                    b.Property<long>("AssignRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Add")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("GuildDiscordId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserDiscordId")
                        .HasColumnType("bigint");

                    b.HasKey("AssignRoleId");

                    b.ToTable("AssignRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
